### ISSUE TITLE
Penumbra (load error) after Dalamud update

### ISSUE THREAD

**Issue by AeraDawn** [xivdev/Penumbra#229]
Ever since dalamud updated ive been getting a load error every time I launch the game with Penumbra enabled. I've tried deleting the mod data and letting it reinstall, but it gives me an install error when I try loading it.

Here's the most recent dalamud.log for the last 2 boot attempts.

[https://pastebin.com/uVhrRVAV](url)

I saw this particular error sequence come up a couple times in the log.

> 2022-07-02 23:23:15.217 -03:00 [ERR] [LOCALPLUGIN] Error while loading Penumbra
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Penumbra.Configuration.Migration.Version1To2() in D:\a\Penumbra\Penumbra\Penumbra\Configuration.Migration.cs:line 101
   at Penumbra.Configuration.Migration.Migrate(Configuration config) in D:\a\Penumbra\Penumbra\Penumbra\Configuration.Migration.cs:line 47
   at Penumbra.Configuration.Load() in D:\a\Penumbra\Penumbra\Penumbra\Configuration.cs:line 99
   at Penumbra.Penumbra..ctor(DalamudPluginInterface pluginInterface) in D:\a\Penumbra\Penumbra\Penumbra\Penumbra.cs:line 78
   --- End of inner exception stack trace ---

**Comment by munkviken** [comment]
Go to your %appdata%\XIVLauncher\pluginconfigs and backing up the penumbra related files/folders, remove them, then try reinstalling.
