### ISSUE TITLE
Could not load type 'System.Runtime.CompilerServices.Unsafe' 

### ISSUE THREAD

**Issue by FlyingStarlight** [xivdev/Penumbra#294]
Hi all devs:

I m new here with a bit technical knowledge
My dalamud cannot load Penumbra with excetption log in below

>2023-03-27 01:04:47.214 +08:00 [ERR] [PLUGINW] Plugin installer threw an unexpected error
>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
> ---> System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.Unsafe' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
>   at Penumbra.Penumbra..ctor(DalamudPluginInterface pluginInterface) in D:\a\Penumbra\Penumbra\Penumbra\Penumbra.cs:line 86
>   --- End of inner exception stack trace ---
>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects)
>   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading)
>   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad)
>   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason)
>2023-03-27 01:05:24.557 +08:00 [INF] Framework::Destroy!
>2023-03-27 01:05:24.557 +08:00 [INF] Trigger unload
>2023-03-27 01:05:24.560 +08:00 [INF] [LOCALPLUGIN] Unloading BetterPlaytime.dll
>2023-03-27 01:05:24.564 +08:00 [INF] [LOCALPLUGIN] Finished unloading BetterPlaytime.dll
>2023-03-27 01:05:25.075 +08:00 [INF] Debug check was not overwritten?
>2023-03-27 01:05:25.082 +08:00 [INF] Saved cache to D:\Dalamud\addon\Hooks\7.3.5.2\cachedSigs\>2023.02.16.0000.0000.json
>2023-03-27 01:05:25.083 +08:00 [INF] Framework::Destroy OK!
>2023-03-27 01:05:25.083 +08:00 [INF] Session has ended.

I have installed .NET SDK 6.0.407 and 7.0.202 with their correspoding Runtime. Other plugins work fine for me.
Other enviroment info:
Windows 11 22H2
Dalamud Version 7.3.5.2
Penumbra Version 0.6.6.5

Hope someone can help me to solve this

Regards.

**Comment by FlyingStarlight** [comment]
I‘ve found the soultion. This issue happened because of different server configuration.
