### ISSUE TITLE
Bug on attempting to import a minion mod pack

### ISSUE THREAD

**Issue by kaerlath** [xivdev/Penumbra#31]
2021-06-09 18:55:46.640 -06:00 [INF] [Penumbra] -> C:\Users\noneofurbusns\Downloads\Wind-up Guitar.ttmp2 START
2021-06-09 18:55:46.671 -06:00 [INF] [Penumbra]     -> Importing Simple V2 ModPack
2021-06-09 18:55:46.674 -06:00 [ERR] [Penumbra] Failed to import modpack at C:\Users\nonofurbusns\Downloads\Wind-up Guitar.ttmp2
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ffxiv\fs_mods\textools-import'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Penumbra.Importer.TexToolsImport.WriteZipEntryToTempFile(Stream s) in D:\a\Penumbra\Penumbra\Penumbra\Importer\TexToolsImport.cs:line 61
   at Penumbra.Importer.TexToolsImport.GetMagicSqPackDeleterStream(ZipFile file, String entryName) in D:\a\Penumbra\Penumbra\Penumbra\Importer\TexToolsImport.cs:line 96
   at Penumbra.Importer.TexToolsImport.ImportSimpleV2ModPack(ZipFile extractedModPack, SimpleModPack modList) in D:\a\Penumbra\Penumbra\Penumbra\Importer\TexToolsImport.cs:line 213
   at Penumbra.Importer.TexToolsImport.VerifyVersionAndImport(FileInfo modPackFile) in D:\a\Penumbra\Penumbra\Penumbra\Importer\TexToolsImport.cs:line 121
   at Penumbra.UI.SettingsInterface.TabImport.<<RunImportTask>b__15_0>d.MoveNext() in D:\a\Penumbra\Penumbra\Penumbra\UI\MenuTabs\TabImport.cs:line 63

**Comment by lmcintyre** [comment]
Did you set your mod folder in the main window? If not, do you have a folder D:/ffxiv/fs_mods/ ?

**Comment by kaerlath** [comment]
I do have that set up as my main mod folder and I do have a folder with that address on my D drive.

**Comment by kaerlath** [comment]
I don't, though, have a folder named textools-import in it.  Am I missing that?  Should that be there?
