### ISSUE TITLE
(Net5) Error handling for missing mod folder

### ISSUE THREAD

**Issue by daemitus** [xivdev/Penumbra#37]
I'm pretty sure I don't have a mod folder anymore. Attempting to open a bad folder path blows the plugin up.

```
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at Penumbra.UI.SettingsInterface.TabSettings.DrawOpenModsButton() in C:\Users\Raymond\code\Penumbra\Penumbra\UI\MenuTabs\TabSettings.cs:line 57
   at Penumbra.UI.SettingsInterface.TabSettings.Draw() in C:\Users\Raymond\code\Penumbra\Penumbra\UI\MenuTabs\TabSettings.cs:line 158
   at Penumbra.UI.SettingsInterface.SettingsMenu.Draw() in C:\Users\Raymond\code\Penumbra\Penumbra\UI\SettingsMenu.cs:line 59
   at Penumbra.UI.SettingsInterface.Draw() in C:\Users\Raymond\code\Penumbra\Penumbra\UI\SettingsInterface.cs:line 34
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\Users\Raymond\code\Dalamud\Dalamud\Interface\UiBuilder.cs:line 235```

**Comment by daemitus** [comment]
Created the directory this time.

```
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at Penumbra.UI.SettingsInterface.TabSettings.DrawOpenModsButton() in C:\Users\Raymond\code\Penumbra\Penumbra\UI\MenuTabs\TabSettings.cs:line 57
   at Penumbra.UI.SettingsInterface.TabSettings.Draw() in C:\Users\Raymond\code\Penumbra\Penumbra\UI\MenuTabs\TabSettings.cs:line 158
   at Penumbra.UI.SettingsInterface.SettingsMenu.Draw() in C:\Users\Raymond\code\Penumbra\Penumbra\UI\SettingsMenu.cs:line 59
   at Penumbra.UI.SettingsInterface.Draw() in C:\Users\Raymond\code\Penumbra\Penumbra\UI\SettingsInterface.cs:line 34
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\Users\Raymond\code\Dalamud\Dalamud\Interface\UiBuilder.cs:line 235
```
