### ISSUE TITLE
Crash on load with entrypoint injection on Linux

### ISSUE THREAD

**Issue by sersorrel** [xivdev/Penumbra#404]
On Linux, using the newly-supported entrypoint injection method, Penumbra crashes on load:

```
2024-03-20 20:32:54.538 +00:00 [INF] [PLUGINM] Loading plugin Penumbra
2024-03-20 20:32:54.542 +00:00 [INF] [PLUGINM] Penumbra defaultState: true wantedByAnyProfile: true loadPlugin: true
2024-03-20 20:32:54.544 +00:00 [INF] [LOCALPLUGIN] Loading Penumbra.dll
2024-03-20 20:32:54.577 +00:00 [DBG] [SVC] Service<FontAtlasFactory>: Construction complete
2024-03-20 20:32:54.577 +00:00 [DBG] [SVC] Service<DalamudInterface>: Begin construction
2024-03-20 20:32:54.577 +00:00 [DBG] [SVC] Service<NotificationManager>: Begin construction
2024-03-20 20:32:54.581 +00:00 [DBG] [SVC] Service<NotificationManager>: Construction complete
2024-03-20 20:32:54.638 +00:00 [DBG] [SVC] Service<DalamudInterface>: Construction complete
2024-03-20 20:32:54.766 +00:00 [ERR] [Penumbra] Error constructing Penumbra, Disposing again:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Penumbra.Services.ValidityChecker.GetGameVersion() in D:\a\Penumbra\Penumbra\Penumbra\Services\ValidityChecker.cs:line 39
   at Penumbra.Services.ValidityChecker..ctor(DalamudPluginInterface pi) in D:\a\Penumbra\Penumbra\Penumbra\Services\ValidityChecker.cs:line 35
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at OtterGui.Services.ServiceManager.<>c__DisplayClass18_0.<AddSingleton>g__Func|0(IServiceProvider p) in D:\a\Penumbra\Penumbra\OtterGui\Services\ServiceManager.cs:line 129
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at OtterGui.Services.ServiceManager.GetService[T]() in D:\a\Penumbra\Penumbra\OtterGui\Services\ServiceManager.cs:line 38
   at Penumbra.Penumbra..ctor(DalamudPluginInterface pluginInterface) in D:\a\Penumbra\Penumbra\Penumbra\Penumbra.cs:line 56
```

I guess `Framework.Instance()` is null very early on startup?

https://github.com/xivdev/Penumbra/blob/fda77b49cdd79a60ede094262473088ca6f2ebf6/Penumbra/Services/ValidityChecker.cs#L38-L39

There is a null check for it elsewhere:

https://github.com/xivdev/Penumbra/blob/fda77b49cdd79a60ede094262473088ca6f2ebf6/Penumbra/Interop/Services/FontReloader.cs#L32-L34

(entrypoint injection may also hang on Linux if Penumbra is enabled, but til this is fixed it's hard to test that)

**Comment by sersorrel** [comment]
1.0.2.1 fixes the crash :) unfortunately we're now back to hanging on startup (before the game window appears) instead

**Comment by Ottermandias** [comment]
Do you have a log for that too?

**Comment by sersorrel** [comment]
Sure: [dalamud.log](https://github.com/xivdev/Penumbra/files/14706065/dalamud.log)

Last couple of lines:

```
2024-03-21 19:20:15.270 +00:00 [VRB] [Penumbra] [BNpcNameDict] Created v3 for English in 427 ms.
2024-03-21 19:20:15.452 +00:00 [VRB] [Penumbra] [Emotes] Created v8 for English in 608 ms.
```

**Comment by randomei** [comment]
For me with version 1.0.2.1 the game loads almost every time. With 1.0.2.5 game successfully loads like 1 of 3 times.. Processes not responding, I must kill them to try again.

**Comment by randomei** [comment]
Version 1.0.2.6 still hanging on startup

**Comment by Ottermandias** [comment]
Try disabling the crash handler in the config json (if you can't get ingame to do it via settings) and tell me if it hangs due to that.

**Comment by randomei** [comment]
Crash handler disabled, still the same.
[dalamud.old.log](https://github.com/xivdev/Penumbra/files/14812305/dalamud.old.log)
[Penumbra.json](https://github.com/xivdev/Penumbra/files/14812307/Penumbra.json)

When I'm returning version 1.0.2.1 - game starting normally:
[dalamud.log](https://github.com/xivdev/Penumbra/files/14812316/dalamud.log)

**Comment by randomei** [comment]
I've tested on another computer, the game starting with version 1.0.2.6. So it seems that the issue is not with penumbra...

**Comment by Ottermandias** [comment]
`2024-03-30 17:45:14.815 +03:00 [INF] [Penumbra] Set new mod base directory from  to .`
this happening sounds kinda weird possibly, in your logs? Can you try on your main PC after setting a root directory maybe?

**Comment by randomei** [comment]
That was some problem with xlcore configuration on main PC, so I've cleaned configuration. Now game starts every time w/o Penumbra and entrypoint enabled. With Penumbra still hangs about 2 of 3 times even w/o mods.
[dalamud.log](https://github.com/xivdev/Penumbra/files/14828854/dalamud.log)

About 1 of 3 times game starting normally.
[dalamud.log](https://github.com/xivdev/Penumbra/files/14828866/dalamud.log)

Same problem with version 1.0.2.6
[dalamud.log](https://github.com/xivdev/Penumbra/files/14828914/dalamud.log)

It seems, that with the latest version it hangs on start even more often.

**Comment by bayta-88** [comment]
Hello I'm on NixOS and I am also experiencing this issue:
Using "DLL injection" method with or without Penumbra: Game always loads correctly
Using "Entrypoint" method without Penumbra: Game always loads correctly
Using "Entrypoint" method with Penumbra: Game loads correctly like 10-20% of the time. Most of the time the XIVLauncher window disappears, the process continues running in the background but the game window never loads and one of the last lines in dalamud.log is "[LOCALPLUGIN] Loading Penumbra.dll".

**Comment by bayta-88** [comment]
I have done some minor modifications of other plugins using Visual Studio on Windows before so I wouldn't mind trying to help with debugging if that helps. Issue is that from what I'm reading in the Dalamud guide plugin development/debugging has to be done with Visual Studio which doesn't seem to be supported on Linux... do you know if it works decently with Wine? Or is there any other way of debugging plugins running on a Linux system?

**Comment by Ottermandias** [comment]
Sorry, but I have no clue.

**Comment by bayta-88** [comment]
Just in case it helps, after some fiddling around I've found that disabling the "Wait for plugins on startup" option under "Advanced" makes Penumbra be loaded correctly every time even when the "Entrypoint" method is chosen but from what I've been told this basically negates the benefits of choosing "Entrypoint" in the first place.
![image](https://github.com/xivdev/Penumbra/assets/138327331/45ca680c-9fcd-43a8-b68f-2485756dffb9)
For me everything seems to be loading correctly tho.

**Comment by bayta-88** [comment]
From what I've been told it appears that the issue is that the Entrypoint method (with the "Wait for plugins on startup" option enabled) stalls the game process while every plugin is being loaded. Apparently stalling the process on Windows is not an issue but when running the game on Wine this causes DXVK to timeout and the game to just not-start. With most plugins the amount of stalling required is not enough to cause problems but with Penumbra if people have enough mods (I have 65GB) this stalling can be long enough to make DXVK timeout causing the problem... if this assessment is correct I think unless some major redesign is done to make Penumbra capable of loading everything much faster (which is likely not possible) or the loading of some mods is delayed the issue is not really solvable... maybe a warning could be added somewhere to let Linux users that if they have too many mods they may need to disable the "Wait for plugins on startup" option and/or pick the "DLLInject" method to make the game start.

**Comment by randomei** [comment]
You may be right. I've tested it on newer and more performant hardware and the game starts every time with stable version. Not tested this with unstable tho.

**Comment by natis1** [comment]
This has been a consistent bugbear for me on seemingly any version of proton 9 regardless of how I load mods (Which is unfortunate because this is also the only version without significant stuttering from shader compiling). Is there any way to disable this dxvk timeout behavior?

**Comment by stascatto** [comment]
@natis1 thought I was the only person with this issue, though I don't know many people who play xiv on linux - penumbra has never worked with any version of wine 9 for me, so i've had to stick with wine 8 but lately some plugins started breaking on wine 8 so had to drop mods, i wonder if its worth making a new issue about this since it seems to be a different problem.
