### ISSUE TITLE
Argument Exception when exporting mod's model through penumbra

### ISSUE THREAD

**Issue by thakyZ** [xivdev/Penumbra#455]
Got an error when exporting a model for a mod to a glTF file:
The error reads as follows:
```
System.ArgumentException: An element with the same key but a different value already exists. Key: 'UV'
at System.Collections.Immutable.ImmutableDictionary`2.HashBucketAdd(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
at System.Collections.Immutable.ImmutableDictionary`2AddRange(lEnumerable`1 items, Mutationlnput origin, KeyCollisionBehavior collisionBehavior)
at System.Collections.Immutable.ImmutableDictionary`2AddRange(lEnumerable`1 pairs, Boolean avoidToHashMap)
at Penumbra.Import.Models.Export.MeshExporter..ctor(ExportConfig& config, MdlFile mdl, Byte lod, UInt16 meshlndex, MaterialBuilder[] materials, Nullable`1 skeleton, IoNotifier notifier) in D:\a\Penumbra\Penumbra\Penumbra\Import\Models\Export\MeshExporter.cs:line 86
at Penumbra.Import.Models.Export.ModelExporter.ConvertMeshes(ExportConfig& config, MdlFile mdl, MaterialBuilder[] materials, Nullable `1 skeleton, IoNotifier notifier) in D:\a\Penumbra\Penumbra\Penumbra\Import\Models\Export\ModelExporter.cs:line 47
at Penumbra.Import.Models.Export.ModelExporter.Export(ExportConfig& config, MdlFile mdl, IEnumerable`1 xivSkeletons, Dictionary`2 rawMaterials, IoNotifier notifier) in D:\a\Penumbra\Penumbra\Penumbra\Import\Models\Export\ModelExporter.cs:line 30
at Penumbra.Import.Models.ModelManager.ExportToGltfAction.Execute(CancellationToken cancel) in D:\a\Penumbra\Penumbra\Penumbra\Import\Models\ModelManager.cs:line 211
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
-- End of stack trace from previous location --
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```
Feel free to contact me if you need more information like what mod is affected same username and on the Discord.

**Comment by Theo-Asterio** [comment]
If the only means to contact you is discord, use the discord to make a proper bug report in the model i/o section.

**Comment by thakyZ** [comment]
An issue has been created on the discord already, will close this.

**Comment by Theo-Asterio** [comment]
SFW was never the concern. We already have the issue listed in Discord (multiple threads). We don't need duplicates and it's generally much better to merge together existing reports along with your own actual settings (not shown) given that's important.
