### ISSUE TITLE
Not hooking into the game or something

### ISSUE THREAD

**Issue by jryn2** [xivdev/Penumbra#51]
for a few days now Penumbra doesn't load with XL, even updated it still won't work

**Comment by Ganom** [comment]
This is the error i'm getting in my logs, if its relevant.
```
2021-09-04 13:10:50.599 -04:00 [ERR] Plugin load for C:\Users\Ganom\AppData\Roaming\XIVLauncher\devPlugins\Penumbra\Penumbra.dll failed.
System.TypeInitializationException: The type initializer for 'Reloaded.Hooks.Tools.Utilities' threw an exception. ---> System.Exception: Unable to find memory location to fit MemoryBuffer of size 65536 (69632) between 1 and 7FFFFFFF.
   at Reloaded.Memory.Buffers.MemoryBufferHelper.Run[T](Int32 retries, Func`1 function)
   at Reloaded.Memory.Buffers.MemoryBufferHelper.Allocate(Int32 size, Int32 minimumAddress, Int32 maximumAddress, Int32 retryCount)
   at Reloaded.Assembler.Assembler.AllocateText(Int32 textSize, Int32 retryCount)
   at Reloaded.Assembler.Assembler..ctor(Int32 textSize, Int32 resultSize)
   at Reloaded.Hooks.Tools.Utilities..cctor()
   --- End of inner exception stack trace ---
   at Reloaded.Hooks.Tools.Utilities.AssembleAbsoluteJump(IntPtr target, Boolean is64bit)
   at Reloaded.Hooks.Hook`1..ctor(TFunction function, Int64 functionAddress, Int32 minHookLength)
   at Penumbra.Interop.ResourceLoader.Init() in D:\a\Penumbra\Penumbra\Penumbra\Interop\ResourceLoader.cs:line 78
   at Penumbra.Plugin.Initialize(DalamudPluginInterface pluginInterface) in D:\a\Penumbra\Penumbra\Penumbra\Plugin.cs:line 72
   at Dalamud.Plugin.PluginManager.LoadPluginFromAssembly(FileInfo dllFile, Boolean isRaw, PluginLoadReason reason, PluginDefinition pluginDef) in C:\goatsoft\companysecrets\dalamud\Plugin\PluginManager.cs:line 359
   at Dalamud.Plugin.PluginManager.LoadSynchronousPlugins() in C:\goatsoft\companysecrets\dalamud\Plugin\PluginManager.cs:line 157
```

**Comment by jryn2** [comment]
I find out what caused my problem, I disabled all mods from Textools to test a new mod I had made. Enabling all mods again lead Penumbra to successfully load three times in a row when mods were enabled
