### ISSUE TITLE
character creation does not load with Penumbra installed

### ISSUE THREAD

**Issue by unknownuserxv** [xivdev/Penumbra#73]
If Penumbra is installed it does not load the character creation, staying stuck on loading in blue screen.

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/141139300-5af062cb-504e-4f17-8272-bc73cb80ec3e.png)

**Comment by unknownuserxv** [comment]
I have had this fail all times related to Penumbra.

**Comment by Ottermandias** [comment]
Well, since it's apparently not a global thing, you either need to provide more information or figure it out yourself.
I assume you have some UI mod that prevents the game from loading a required button or something like that.

**Comment by unknownuserxv** [comment]
This is what resulted from posting the log on discord, only Penumbra is mntioned, if I delete Penumbra it works, if I add Penumbra it doesn't so how can it be something besides Penumbra? No new mod was installed, there was just a maint and that's it. I don't use UI mods actually.

Dalamud.log parse results for LASTEXCEPTION
Franzbot has parsed your logfile. Here's some information about the last issue found in your log file.
Info
System.BadImageFormatException: Could not load file or assembly 'Penumbra, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)File name: 'Penumbra, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly)
Info continued
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadAssemblyFromFilePath(String path) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Loader\ManagedLoadContext.cs:line 115   at Dalamud.Plugin.Internal.Loader.PluginLoader.LoadDefaultAssembly() in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Loader\PluginLoader.cs:line 92   at Dalamud.Plugin.Internal.LocalPlugin..ctor(FileInfo dllFile, LocalPluginManifest manifest) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\LocalPlugin.cs:line 55
Context
[LOCALPLUGIN] Not a plugin: C:\Users\ptwts\AppData\Roaming\XIVLauncher\devPlugins\ref\Penumbra.dll
System.BadImageFormatException: Could not load file or assembly 'Penumbra, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)File name: 'Penumbra, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
Context continued
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly)   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadAssemblyFromFilePath(String path) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Loader\ManagedLoadContext.cs:line 115   at Dalamud.Plugin.Internal.Loader.PluginLoader.LoadDefaultAssembly() in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Loader\PluginLoader.cs:line 92   at Dalamud.Plugin.Internal.LocalPlugin..ctor(FileInfo dllFile, LocalPluginManifest manifest) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\LocalPlugin.cs:line 55
Timestamp
2021-11-10T06:48:32.3649619-03:00
Quarta-feira, 10 de novembro de 2021 às 06:48
Franzbot version: 2021-October-03

**Comment by reiichi001** [comment]
Nobody should be manually installing Penumbra anymore. That also looks to be an old API 3 version for Dalamud < 6. You should delete those old plugin files and switch to using the 3rd party repo and see if you can reproduce the issue.

Type `/xlsettings` in game, go to the Experimental tab, and add <https://raw.githubusercontent.com/xivdev/Penumbra/master/repo.json> (hit the + sign after). Then save and close. 

You'll be able to install Penumbra in-game and will get updates for it too.

**Comment by unknownuserxv** [comment]
I did what you said, also other steps like disabling other plugins and reinstalling ffxivlauncher, if Penumbra is enabled neither character creation or aesthetician load, I disable it and it works. I got no replies in discord so took the problem here.

**Comment by Ottermandias** [comment]
What mods are you loading, what is your configuration, what have you tried, have you been using TexTools beforehand, have you done a cleanup with it...

**Comment by unknownuserxv** [comment]
I tried with very few mods that I've been using forever since several Penumbra versions, mostly hair mods done by TT, somehave conflicts with themselves but that's all but I have few and most are disabled since I load one by character, I use TT also with few mods like body mods and didn't install nothing new, there was no change or new mod to it during the time that I started having this issue in neither one, I disabled Penumbra, cc and aest work, enable loading blue/black screen stuck, I stayed with Penumbra abled and all other plugins disabled. Shouldn't TT still continue the problem when Penumbra is disabled if that's the cause. Last TT change was last bigger maint, just a backup modpack.

**Comment by Ottermandias** [comment]
It would be far easier to screenshot your settings, collections and possibly mod list than vaguely describing them.
